global:
  slack_api_url: 'https://hooks.slack.com/services/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'

  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: alertmanager@example.com
  smtp_auth_username: alertmanager
  smtp_auth_password: email_auth_token

route:
  receiver: 'email-notifications'
  routes:
    - continue: true
    - receiver: 'slack-notifications'
    - receiver: 'email-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#andrei_bogomja'
- name: 'email-notifications'
  email_configs:
  - to: alertmanager@example.com
