global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#andrei_bogomja'
