version: '3.6'
services:
  post_db:
    image: 'mongo:${MONGO_VERSION}'
    volumes:
      - 'post_db:/data/db'
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: '${USER_NAME}/ui:${VERSION}'
    ports:
      - '${PUMA_PORT}:${PUMA_PORT}/tcp'
    networks:
      - front_net
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: '${USER_NAME}/post:${VERSION}'
    networks:
      - front_net
      - back_net
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: '${USER_NAME}/comment:${VERSION}'
    networks:
      - front_net
      - back_net

volumes:
  post_db:
    name: post_db

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
    name: back_net
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
    name: front_net
